# `dep` does not seem to like this empty directory in the Kubernetes
# repository.
ignored = ["k8s.io/kubernetes/pkg/api"]

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "google.golang.org/api"
  revision = "373a4c220f5c90e5b7ff7101779c5be385d171be"

[[constraint]]
  name = "k8s.io/api"
  # We are currently vendoring a non-released k8s version. This should go away
  # once the symbol has been released.
  revision = "02509811a0e5c1e5bb0656e31ec861da05cd801c"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "7652c252d4ce2aea1563853bef0438769c5781fd"

[[constraint]]
  name = "github.com/docker/distribution"
  # Kubernetes is currently vendoring a non-released version. One of the
  # symbols needed is not longer there in the released tag.
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[[constraint]]
  branch = "master"
  name = "k8s.io/cluster-registry"
